### ISSUE TITLE
Automate release and deployment

### ISSUE THREAD

**Issue by stieg** [Airfordable/ecs-deploy-task-definition-to-scheduled-task#9]
Need to automate this deployment to make project easier to maintain.  Ideally deployment would happen if we pushed a signed tag to the `main` branch.  However there is the issue where the updated code has to be available for GitHub actions to use (I am not aware if it being able to use a build artifact at this time... I hope there is a way it can). Ticket tracks figuring out best way to automate this release process and keep it sane.

**Comment by spyoungtech** [comment]
Could consider using the [create-release](https://github.com/actions/create-release) action, which should do the trick.

A trigger condition like this should get what you want.

```
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Push events to matching semver-like string, i.e. v1.0, v20.15.10
```

New GitHub Actions versions get released to the marketplace upon creation of a release, so, this should work for that use case.
